name: Test Pipeline

on: [push]

env:
  CYPRESS_MAILSLURP_API_KEY: ${{secrets.CYPRESS_MAILSLURP_API_KEY}}

jobs:
  cypress-job:
    runs-on: ubuntu-latest

    steps:
    - name: Setup
      uses: actions/checkout@v4

    - name: Run Cypress Test
      uses: cypress-io/github-action@v6
      with:
        record: true
        parallel: true
      env:
        CYPRESS_MAILSLURP_API_KEY: ${{env.secrets.CYPRESS_MAILSLURP_API_KEY}}
        CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
      
    - run: node report.js

    - name: Save Report
      uses: actions/upload-artifact@v2
      with: 
        name: test-reports
        path: |
          cypress/reports/html/cucumber-report/

    - name: Run Cross Browser Testing
      uses: browserstack/github-actions/setup-env@master
      with:
        username: ${{secrets.BROWSERSTACK_USERNAME}}
        access-key: ${{secrets.BROWSERSTACK_ACCESS_KEY}}

    - run: npm i
    - run: npx browserstack-cypress run
